# Generated by Django 6.0.4 on 2026-05-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudGarantiaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_serial', models.CharField(max_length=100)),
                ('garantia_id', models.IntegerField()),
                ('reportado_por', models.CharField(max_length=200)),
                ('descripcion_falla', models.TextField()),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='nueva', max_length=50)),
            ],
            options={
                'db_table': 'solicitudes_garantia',
            },
        ),
    ]
