# Generated by Django 6.0.4 on 2026-05-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorradorCorreoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud_id', models.IntegerField()),
                ('destinatario_tipo', models.CharField(max_length=50)),
                ('destinatario_email', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=300)),
                ('cuerpo', models.TextField()),
                ('estado', models.CharField(default='pendiente_aprobacion', max_length=50)),
                ('aprobado_por', models.EmailField(blank=True, max_length=254, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'borradores_correo',
            },
        ),
        migrations.CreateModel(
            name='EventoSeguimientoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud_id', models.IntegerField()),
                ('tipo_evento', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('dias_sin_respuesta', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'eventos_seguimiento',
            },
        ),
    ]
