# Generated by Django 6.0.4 on 2026-05-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoTrazabilidadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_id', models.CharField(max_length=100)),
                ('solicitud_id', models.IntegerField()),
                ('ubicacion_anterior', models.CharField(max_length=200)),
                ('ubicacion_nueva', models.CharField(max_length=200)),
                ('responsable', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metodo_registro', models.CharField(default='manual', max_length=50)),
            ],
            options={
                'db_table': 'eventos_trazabilidad',
            },
        ),
    ]
