# Generated by Django 6.0.4 on 2026-05-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventotrazabilidadmodel',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
