# Generated by Django 6.0.4 on 2026-05-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(max_length=254)),
                ('tipo', models.CharField(max_length=100)),
                ('canal', models.CharField(default='email', max_length=50)),
                ('estado', models.CharField(default='enviada', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'notificaciones',
            },
        ),
    ]
